#!/usr/bin/python3 -u

# 2022 eCTF
# Protect Configuration Tool
# 0xDACC
#
# This tool meets all functional and security requiremnets. The way this tool works is prettyt neat actually and took some thought.
# It packs on a 16 byte password for authentication onto the end of the data, which is then encrypted along side the rest of the data.
# Due to the nature of CBC decryption, and since the password is at the very end, if any byte before the password is messed with before decryption, then the password wont decrypt right.
# Authentication and integrity combined into one step! Now that's efficient!

import argparse
import logging
from pathlib import Path
from Crypto.Cipher import AES

from util import print_banner, CONFIGURATION_ROOT, LOG_FORMAT

logging.basicConfig(level=logging.INFO, format=LOG_FORMAT)
log = logging.getLogger(Path(__file__).name)


def protect_configuration(raw_cfg: Path, protected_cfg: Path):
    print_banner("SAFFIRe Configuration Protect Tool")

    # Read in the raw configuration binary
    log.info("Reading configuration data...")
    file_data = raw_cfg.read_bytes()

    log.info("Encrypting the configuration...")

    # Read the crypto info from the host secrets files
    key = Path("/secrets/key").read_bytes()
    iv = Path("/secrets/iv").read_bytes()
    password = Path("/secrets/password").read_bytes()

    # We will also pad on extra data to make it divisible by 1024, which will make it easier to do the next few steps.
    padded_cfg = file_data
    padded_cfg += (b'\xFF' * ((1024 - len(file_data) % 1024) % 1024))

    # string which will hold the completed cfg protect file
    encrypted_cfg = b''

    # Now we split the padded config by every 1kb and do two things: 1) pack password to end of 1kb section, 2)encrypt each 1kb section
    for i in range(0, (len(padded_cfg) / 1024)):
        # Slice into 1kb frames
        frame = padded_cfg[(i*1024):((i+1)*1024)]

        # Add password
        frame += password

        # creating new aes object.
        cipher = AES.new(key, AES.MODE_CBC, iv)

        # encrypt
        enc_frame = cipher.encrypt(frame)

        #combine
        encrypted_cfg += enc_frame

    log.info("Packaging the configuration...")

    # Write to the output file
    protected_cfg.write_bytes(encrypted_cfg)

    log.info("Configuration protected\n")


def main():
    # get arguments
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input-file", help="The name of the configuration to protect.", required=True
    )
    parser.add_argument(
        "--output-file", help="The name of the protected configuration.", required=True
    )

    args = parser.parse_args()

    # process command
    raw_cfg = CONFIGURATION_ROOT / args.input_file
    protected_cfg = CONFIGURATION_ROOT / args.output_file
    protect_configuration(raw_cfg, protected_cfg)


if __name__ == "__main__":
    main()
