#!/usr/bin/python3 -u

# 2022 eCTF
# EEPROM Setup tool
# 0xDACC
#
# This tool is almost criminally simple. In fact it should probably be a function inside another tool
# But I made it this way for a reason and there's no way I'm going back and messing with perfectly functional code!

from pathlib import Path

key = Path("/secrets/key").read_bytes()
iv = Path("/secrets/iv").read_bytes()
password = Path("/secrets/password").read_bytes()
source_eeprom = Path("/bootloader/eeprom.bin")


def main():
    # Write key and iv to eeprom in sequence
    source_eeprom.write_bytes(key + iv + password)

    return 0

if __name__ == "__main__":
    main()
